### ISSUE TITLE
Bug where I can't swing shovel when attacked by some enemies

### ISSUE THREAD

**Issue by AddisontheAzelf** [ButteryStancakes/MeleeFixes#3]
I've been encountering this bug when attacked by the snare flea and the kidnapper fox where after these two enemies make me drop my items I can't swing my shovel. I disabled the mod and the problem disappears.

**Comment by ButteryStancakes** [comment]
I'm leaning towards the side of this being a mod conflict, because my friends and I have never been able to replicate this issue when we play.

This mod does include a tentative fix for a shovel becoming unusable if you die holding it and your team recovers it for you, which sounds like it'd be related to this issue (since you are forced to drop all your items, just like in death), but I've never been able to replicate that bug either so I don't know if my "fix" works

Out of curiosity, are you hosting your games? And do you have a Player.log where you've encountered the error, just in case it has some useful info?

**Comment by AddisontheAzelf** [comment]
i Re-enabled MeleeFixes to try to get a player.log when i encountered the bug again and now i can't seem to get the issue to happen again.

**Comment by NakiriFox** [comment]
The same issue and there is no log available.
This issue is not 100% likely to occur, sometimes I can swing a shovel after being attacked, sometimes I can't.

**Comment by NakiriFox** [comment]
I will try to reproduce it using debug_menu and MeleeFix

**Comment by NakiriFox** [comment]
It is indeed a mod conflict, and this issue does not exist when I only install MeleeFix and Debug_Menu

**Comment by NakiriFox** [comment]
I solved it, it was entirely caused by the DoorReach Mod👇
https://thunderstore.io/c/lethal-company/p/Nyxchrono/DoorBreach/

**Comment by ButteryStancakes** [comment]
Noted, thank you for investigating that
